"""
Description:
    This program implements a simple Twitter bot that tweets information about bills in Congress
    that are (in)directly related to cyber issues. This bot uses a MySQL database backend to
    keep track of bills, both posted and unposted (i.e., tweeted and yet to be tweeted, respectively).
    For this initial proof of concept, bill data are scraped from the official US Government
    Publishing Office website. For future versions, it would probably be better to connect to a
    less cumbersome endpoint like ProPublica.

Module:
    This module containts all program constants.

Libraries:
    This program makes use of the following libraries:
        lxml
            Stephan Richter / Infrae
            BSD License
            http://lxml.de/

        xmltodict        
            Martin Blech & contribs.    
            MIT License
            https://github.com/martinblech/xmltodict

        python-twitter    
            Mike Taylor ('bear') & contribs.
            Apache License 2.0
            https://github.com/bear/python-twitter

        requests
            Kenneth Reitz
            Apache License 2.0
            http://docs.python-requests.org/en/master

        MySQL Connector
            Oracle & affiliates
            Misc. License
            https://dev.mysql.com/doc/connector-python/en/

License:
    Copyright 2017 J. Michael Beaver

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

References:
    https://www.gpo.gov/fdsys/bulkdata/BILLSTATUS/resources/BILLSTATUS-XML_User-Guide-v1.pdf
    https://github.com/usgpo/bill-status/blob/master/BILLSTATUS-XML_User_User-Guide.md
    https://projects.propublica.org/api-docs/congress-api/endpoints/
    https://github.com/bear/python-twitter
    https://github.com/martinblech/xmltodict
    http://docs.python-requests.org/en/master
    https://dev.mysql.com/doc/connector-python/en/
    http://lxml.de/
    https://www.python.org/dev/peps/pep-0249
    https://is.gd/apishorteningreference.php
    https://www.pantz.org/software/mysql/mysqlcommands.html
    https://bitbucket.org/ned/coveragepy/commits/f8e9d62f1412
    https://www.govtrack.us/api/v2/role
    https://choosealicense.com/licenses/apache-2.0/
    http://www.mysqltutorial.org/getting-started-mysql-python-connector/
"""
__version__ = '0.1'

"""
Annoying stopgap: Twitter reserves some space for their t.co 'shortened' links.
That's 23-24 characters. Just going for a safe upper bound here. See:
    https://github.com/bear/python-twitter/issues/265
    https://github.com/bear/python-twitter/issues/457
"""
TWEET_MAX_LENGTH = 116  # 140 - 24 
SLEEP_LIMIT = 8

KEYWORDS = ['cyber',
            'hacking',
            'hacker',
            'hacked',
            'breach',
            'privacy',
            'Internet',
            'broadband',
            'crypto',
            'net neutrality',
            'communications',
            'fcc']
            #'hack',
            #'leak',
            #'nsa',
            #'data',
            #'technology',
            #'digital',
            #'security']

CONGRESS  = '115'
ROOT_URL  = 'https://www.gpo.gov/fdsys/'
BULK_PATH = 'bulkdata/BILLSTATUS/'
BASE_URL  = ROOT_URL + BULK_PATH + CONGRESS

SENATE_URL  = BASE_URL + '/s/'
SRES_URL    = BASE_URL + '/sres/'
SJRES_URL   = BASE_URL + '/sjres/'
SCONRES_URL = BASE_URL + '/sconres/'
HOUSE_URL   = BASE_URL + '/hr/'
HRES_URL    = BASE_URL + '/hres/'
HJRES_URL   = BASE_URL + '/hjres/'
HCONRES_URL = BASE_URL + '/hconres/'

URL_LIST = [SENATE_URL,
            SRES_URL,
            SJRES_URL,
            SCONRES_URL,
            HOUSE_URL,
            HRES_URL,
            HJRES_URL,
            HCONRES_URL]

CONGRESS_URL = 'https://www.congress.gov/bill/'
BILL_TYPES_PATH = {'S':       'senate-bill',
                 'SRES':    'senate-resolution',
                 'SJRES':   'senate-joint-resolution',
                 'SCONRES': 'senate-concurrent-resolution',
                 'HR':      'house-bill',
                 'HRES':    'house-resolution',
                 'HJRES':   'house-joint-resolution',
                 'HCONRES': 'house-concurrent-resolution'}

CONGRESS_TWITTER = {
                    'Brown, Sherrod': '@SenSherrodBrown',
                    'Cantwell, Maria': '@SenatorCantwell',
                    'Cardin, Benjamin': '@SenatorCardin',
                    'Carper, Thomas': '@SenatorCarper',
                    'Casey, Robert': '@SenBobCasey',
                    'Corker, Bob': '@SenBobCorker',
                    'Feinstein, Dianne': '@SenFeinstein',
                    'Hatch, Orrin': '@SenOrrinHatch',
                    'Klobuchar, Amy': '@amyklobuchar _',
                    'McCaskill, Claire': '@McCaskillOffice',
                    'Menendez, Robert': '@SenatorMenendez',
                    'Nelson, Bill': '@SenBillNelson',
                    'Sanders, Bernard': '@SenSanders',
                    'Stabenow, Debbie': '@SenStabenow',
                    'Tester, Jon': '@SenatorTester',
                    'Whitehouse, Sheldon': '@SenWhitehouse',
                    'Barrasso, John': '@SenJohnBarrasso',
                    'Wicker, Roger': '@SenatorWicker',
                    'Alexander, Lamar': '@SenAlexander',
                    'Cochran, Thad': '@SenThadCochran',
                    'Collins, Susan': '@SenatorCollins',
                    'Cornyn, John': '@JohnCornyn',
                    'Durbin, Richard': '@SenatorDurbin',
                    'Enzi, Michael': '@SenatorEnzi',
                    'Graham, Lindsey': '@GrahamBlog',
                    'Inhofe, James': '@InhofePress',
                    'McConnell, Mitch': '@McConnellPress',
                    'Merkley, Jeff': '@SenJeffMerkley',
                    'Reed, John': '@SenJackReed',
                    'Risch, James': '@SenatorRisch',
                    'Roberts, Pat': '@SenPatRoberts',
                    'Shaheen, Jeanne': '@SenatorShaheen',
                    'Udall, Tom': '@SenatorTomUdall',
                    'Warner, Mark': '@MarkWarner',
                    'Gillibrand, Kirsten': '@SenGillibrand',
                    'Franken, Alan': '@SenFranken',
                    'Coons, Chris': '@SenCoonsOffice',
                    'Manchin, Joe': '@Sen_JoeManchin',
                    'Aderholt, Robert': '@Robert_Aderholt',
                    'Amash, Justin': '@justinamash',
                    'Baldwin, Tammy': '@SenatorBaldwin',
                    'Barletta, Lou': '@RepLouBarletta',
                    'Barton, Joe': '@RepJoeBarton',
                    'Bass, Karen': '@RepKarenBass',
                    'Bennet, Michael': '@SenBennetCo',
                    'Bilirakis, Gus': '@RepGusBilirakis',
                    'Bishop, Rob': '@RepRobBishop',
                    'Bishop, Sanford': '@SanfordBishop',
                    'Black, Diane': '@RepDianeBlack',
                    'Blackburn, Marsha': '@MarshaBlackburn',
                    'Blumenauer, Earl': '@BlumenauerMedia',
                    'Blumenthal, Richard': '@SenBlumenthal',
                    'Blunt, Roy': '@RoyBlunt',
                    'Boozman, John': '@JohnBoozman',
                    'Bordallo, Madeleine': None,
                    'Brady, Kevin': '@RepKevinBrady',
                    'Brady, Robert': '@RepBrady',
                    'Brooks, Mo': '@RepMoBrooks',
                    'Buchanan, Vern': '@VernBuchanan',
                    'Bucshon, Larry': '@RepLarryBucshon',
                    'Burgess, Michael': '@MichaelCBurgess',
                    'Burr, Richard': '@SenatorBurr',
                    'Butterfield, George': '@GKButterfield',
                    'Calvert, Ken': '@KenCalvert',
                    'Capito, Shelley': '@SenCapito',
                    'Capuano, Michael': '@RepMikeCapuano',
                    'Carson, Andre': '@RepAndreCarson',
                    'Carter, John': '@JudgeCarter',
                    'Cassidy, Bill': '@BillCassidy',
                    'Castor, Kathy': '@USRepKCastor',
                    'Chabot, Steve': '@RepSteveChabot',
                    'Chaffetz, Jason': '@JasonInTheHouse',
                    'Chu, Judy': '@RepJudyChu',
                    'Cicilline, David': '@RepCicilline',
                    'Clarke, Yvette': '@RepYvetteClarke',
                    'Clay, Wm.': None,
                    'Cleaver, Emanuel': '@RepCleaver',
                    'Clyburn, James': '@Clyburn',
                    'Coffman, Mike': '@RepMikeCoffman',
                    'Cohen, Steve': '@RepCohen',
                    'Cole, Tom': '@TomColeOK04',
                    'Conaway, K.': '@ConawayTX11',
                    'Connolly, Gerald': '@GerryConnolly',
                    'Conyers, John': '@RepJohnConyers',
                    'Cooper, Jim': '@RepJimCooper',
                    'Costa, Jim': '@RepJimCosta',
                    'Courtney, Joe': '@RepJoeCourtney',
                    'Crapo, Michael': '@MikeCrapo',
                    'Crawford, Eric': '@RepRickCrawford',
                    'Crowley, Joseph': '@RepJoeCrowley',
                    'Cuellar, Henry': '@RepCuellar',
                    'Culberson, John': '@CongCulberson',
                    'Cummings, Elijah': '@RepCummings',
                    'Davis, Danny': '@RepDannyDavis',
                    'Davis, Susan': '@RepSusanDavis',
                    'DeFazio, Peter': '@RepPeterDeFazio',
                    'DeGette, Diana': '@RepDianaDeGette',
                    'DeLauro, Rosa': '@RosaDeLauro',
                    'Denham, Jeff': '@RepJeffDenham',
                    'Dent, Charles': '@RepCharlieDent',
                    'DesJarlais, Scott': '@DesJarlaisTN04',
                    'Deutch, Theodore': '@RepTedDeutch',
                    'Diaz-Balart, Mario': '@MarioDB',
                    'Doggett, Lloyd': '@RepLloydDoggett',
                    'Donnelly, Joe': '@SenDonnelly',
                    'Doyle, Michael': '@USRepMikeDoyle',
                    'Duffy, Sean': '@RepSeanDuffy',
                    'Duncan, Jeff': '@RepJeffDuncan',
                    'Duncan, John': '@RepJohnDuncanJr',
                    'Ellison, Keith': '@KeithEllison',
                    'Engel, Eliot': '@RepEliotEngel',
                    'Eshoo, Anna': '@RepAnnaEshoo',
                    'Farenthold, Blake': '@Farenthold',
                    'Flake, Jeff': '@JeffFlake',
                    'Fleischmann, Charles': '@RepChuck',
                    'Flores, Bill': '@RepBillFlores',
                    'Fortenberry, Jeff': '@JeffFortenberry',
                    'Foxx, Virginia': '@VirginiaFoxx',
                    'Franks, Trent': '@RepTrentFranks',
                    'Frelinghuysen, Rodney': '@USRepRodney',
                    'Fudge, Marcia': '@RepMarciaFudge',
                    'Garamendi, John': '@RepGaramendi',
                    'Gardner, Cory': '@SenCoryGardner',
                    'Gibbs, Bob': '@RepBobGibbs',
                    'Gohmert, Louie': '@RepLouieGohmert',
                    'Goodlatte, Bob': '@RepGoodlatte',
                    'Gosar, Paul': '@RepGosar',
                    'Gowdy, Trey': '@TGowdySC',
                    'Granger, Kay': '@RepKayGranger',
                    'Grassley, Charles': '@ChuckGrassley',
                    'Graves, Sam': '@RepSamGraves',
                    'Graves, Tom': '@RepTomGraves',
                    'Green, Al': '@RepAlGreen',
                    'Green, Gene': '@RepGeneGreen',
                    'Griffith, H.': '@RepMGriffith',
                    'Grijalva, Raul': '@RepraulGrijalva',
                    'Guthrie, Brett': '@RepGuthrie',
                    'Gutierrez, Luis': '@RepGutierrez',
                    'Harper, Gregg': '@GreggHarper',
                    'Harris, Andy': '@RepAndyHarrisMD',
                    'Hartzler, Vicky': '@RepHartzler',
                    'Hastings, Alcee': '@RepHastingsFL',
                    'Heinrich, Martin': '@MartinHeinrich',
                    'Hensarling, Jeb': '@RepHensarling',
                    'Herrera Beutler, Jaime': '@HerreraBeutler',
                    'Higgins, Brian': '@RepBrianHiggins',
                    'Himes, James': '@JAHimes',
                    'Hirono, Mazie': '@MazieHirono',
                    'Hoeven, John': '@SenJohnHoeven',
                    'Hoyer, Steny': '@WhipHoyer',
                    'Huizenga, Bill': '@RepHuizenga',
                    'Hultgren, Randy': '@RepHultgren',
                    'Hunter, Duncan': '@Rep_Hunter',
                    'Isakson, John': '@SenatorIsakson',
                    'Issa, Darrell': '@DarrellIssa',
                    'Jackson Lee, Sheila': '@JacksonLeeTX18',
                    'Jenkins, Lynn': '@RepLynnJenkins',
                    'Johnson, Bill': '@RepBillJohnson',
                    'Johnson, Eddie': '@RepEBJ',
                    'Johnson, Henry': '@RepHankJohnson',
                    'Johnson, Ron': '@SenRonJohnson',
                    'Johnson, Sam': '@SamsPressShop',
                    'Jones, Walter': '@RepWalterJones',
                    'Jordan, Jim': '@Jim_Jordan',
                    'Kaptur, Marcy': '@RepMarcyKaptur',
                    'Keating, William': '@USRepKeating',
                    'Kelly, Mike': '@MikeKellyPA',
                    'Kind, Ron': '@RepRonKind',
                    'King, Peter': '@RepPeteKing',
                    'King, Steve': '@SteveKingIA',
                    'Kinzinger, Adam': '@RepKinzinger',
                    'Labrador, Raul': '@Raul_Labrador',
                    'Lamborn, Doug': '@RepDLamborn',
                    'Lance, Leonard': '@RepLanceNJ7',
                    'Langevin, James': '@JimLangevin',
                    'Lankford, James': '@SenatorLankford',
                    'Larsen, Rick': '@RepRickLarsen',
                    'Larson, John': '@RepJohnLarson',
                    'Latta, Robert': '@BobLatta',
                    'Leahy, Patrick': '@SenatorLeahy',
                    'Lee, Barbara': '@RepBarbaraLee',
                    'Lee, Mike': '@SenMikeLee',
                    'Levin, Sander': '@RepSandyLevin',
                    'Lewis, John': '@RepJohnLewis',
                    'Lipinski, Daniel': '@RepLipinski',
                    'LoBiondo, Frank': '@RepLoBiondo',
                    'Loebsack, David': '@DaveLoebsack',
                    'Lofgren, Zoe': '@RepZoeLofgren',
                    'Long, Billy': '@USRepLong',
                    'Lowey, Nita': '@NitaLowey',
                    'Lucas, Frank': '@RepFrankLucas',
                    'Luetkemeyer, Blaine': '@RepBlainePress',
                    'Lujan, Ben': '@RepBenRayLujan',
                    'Lynch, Stephen': '@RepStephenLynch',
                    'Maloney, Carolyn': '@RepMaloney',
                    'Marchant, Kenny': '@RepKenMarchant',
                    'Marino, Tom': '@RepTomMarino',
                    'Markey, Edward': '@SenMarkey',
                    'Matsui, Doris': '@DorisMatsui',
                    'McCain, John': '@SenJohnMcCain',
                    'McCarthy, Kevin': '@GOPLeader',
                    'McCaul, Michael': '@RepMcCaul',
                    'McClintock, Tom': '@RepMcClintock',
                    'McCollum, Betty': '@BettyMcCollum04',
                    'McGovern, James': '@RepMcGovern',
                    'McHenry, Patrick': '@PatrickMcHenry',
                    'McKinley, David': '@RepMcKinley',
                    'McMorris Rodgers, Cathy': '@CathyMcMorris',
                    'McNerney, Jerry': '@RepMcNerney',
                    'Meehan, Patrick': '@RepMeehan',
                    'Meeks, Gregory': '@GregoryMeeks',
                    'Moore, Gwen': '@RepGwenMoore',
                    'Moran, Jerry': '@JerryMoran',
                    'Murkowski, Lisa': '@LisaMurkowski',
                    'Murphy, Christopher': '@senmurphyoffice',
                    'Murphy, Tim': '@RepTimMurphy',
                    'Murray, Patty': '@PattyMurray',
                    'Nadler, Jerrold': '@RepJerryNadler',
                    'Napolitano, Grace': '@GraceNapolitano',
                    'Neal, Richard': '@RepRichardNeal',
                    'Noem, Kristi': '@RepKristiNoem',
                    'Norton, Eleanor': '@EleanorNorton',
                    'Nunes, Devin': '@Rep_DevinNunes',
                    'Olson, Pete': '@RepPeteOlson',
                    'Palazzo, Steven': '@CongPalazzo',
                    'Pallone, Frank': '@FrankPallone',
                    'Pascrell, Bill': '@BillPascrell',
                    'Paul, Rand': '@RandPaul',
                    'Paulsen, Erik': '@RepErikPaulsen',
                    'Pearce, Stevan': '@RepStevePearce',
                    'Pelosi, Nancy': 'NonecyPelosi',
                    'Perlmutter, Ed': '@RepPerlmutter',
                    'Peters, Gary': '@SenGaryPeters',
                    'Peterson, Collin': '@collinpeterson',
                    'Pingree, Chellie': '@ChelliePingree',
                    'Poe, Ted': '@JudgeTedPoe',
                    'Polis, Jared': '@RepJaredPolis',
                    'Portman, Robert': '@SenRobPortman',
                    'Posey, Bill': '@CongBillPosey',
                    'Price, David': '@RepDavidEPrice',
                    'Quigley, Mike': '@RepMikeQuigley',
                    'Reed, Tom': '@RepTomReed',
                    'Reichert, David': '@DaveReichert',
                    'Renacci, James': '@RepJimRenacci',
                    'Richmond, Cedric': '@RepRichmond',
                    'Roby, Martha': '@RepMarthaRoby',
                    'Roe, David': '@DrPhilRoe',
                    'Rogers, Harold': '@RepHalRogers',
                    'Rogers, Mike': '@RepMikeRogersAL',
                    'Rohrabacher, Dana': '@reprohrabacher',
                    'Rokita, Todd': '@ToddRokita',
                    'Rooney, Thomas': '@TomRooney',
                    'Ros-Lehtinen, Ileana': '@RosLehtinen',
                    'Roskam, Peter': '@PeterRoskam',
                    'Ross, Dennis': '@RepDennisRoss',
                    'Roybal-Allard, Lucille': '@RepRoybalAllard',
                    'Royce, Edward': '@RepEdRoyce',
                    'Rubio, Marco': '@SenRubioPress',
                    'Ruppersberger, C.': '@Call_Me_Dutch',
                    'Rush, Bobby': '@RepBobbyRush',
                    'Ryan, Paul': '@SpeakerRyan',
                    'Ryan, Tim': '@RepTimRyan',
                    'Sablan, Gregorio': None,
                    'Sarbanes, John': '@RepSarbanes',
                    'Scalise, Steve': '@SteveScalise',
                    'Schakowsky, Janice': '@JanSchakowsky',
                    'Schiff, Adam': '@RepAdamSchiff',
                    'Schrader, Kurt': '@RepSchrader',
                    'Schumer, Charles': '@SenSchumer',
                    'Schweikert, David': '@RepDavid',
                    'Scott, Austin': '@AustinScottGA08',
                    'Scott, David': '@RepDavidScott',
                    'Scott, Robert': '@BobbyScott',
                    'Scott, Tim': '@SenatorTimScott',
                    'Sensenbrenner, F.': '@JimPressOffice',
                    'Serrano, Jose': '@RepJoseSerrano',
                    'Sessions, Pete': '@PeteSessions',
                    'Sewell, Terri': '@RepTerriSewell',
                    'Shelby, Richard': '@SenShelby',
                    'Sherman, Brad': '@BradSherman',
                    'Shimkus, John': '@RepShimkus',
                    'Shuster, Bill': '@RepBillShuster',
                    'Simpson, Michael': '@CongMikeSimpson',
                    'Sires, Albio': '@RepSires',
                    'Slaughter, Louise': '@LouiseSlaughter',
                    'Smith, Adam': '@RepAdamSmith',
                    'Smith, Adrian': '@RepAdrianSmith',
                    'Smith, Christopher': '@RepChrisSmith',
                    'Smith, Lamar': '@LamarSmithTX21',
                    'Speier, Jackie': '@RepSpeier',
                    'Stivers, Steve': '@RepSteveStivers',
                    'Sanchez, Linda': '@RepLindaSanchez',
                    'Thompson, Bennie': '@BennieGThompson',
                    'Thompson, Mike': '@RepThompson',
                    'Thompson, Glenn': '@CongressmanGT',
                    'Thornberry, Mac': '@MacTXPress',
                    'Thune, John': '@SenJohnThune',
                    'Tiberi, Patrick': '@pattiberi',
                    'Tipton, Scott': '@RepTipton',
                    'Tonko, Paul': '@RepPaulTonko',
                    'Toomey, Patrick': '@SenToomey',
                    'Tsongas, Niki': '@NikiInTheHouse',
                    'Turner, Michael': '@RepMikeTurner',
                    'Upton, Fred': '@RepFredUpton',
                    'Van Hollen, Chris': '@ChrisVanHollen',
                    'Velazquez, Nydia': '@NydiaVelazquez',
                    'Visclosky, Peter': '@RepVisclosky',
                    'Walberg, Tim': '@RepWalberg',
                    'Walden, Greg': '@RepGregWalden',
                    'Walz, Timothy': '@RepTimWalz',
                    'Wasserman Schultz, Debbie': '@RepDWStweets',
                    'Waters, Maxine': '@MaxineWaters',
                    'Webster, Daniel': '@RepWebster',
                    'Welch, Peter': '@PeterWelch',
                    'Wilson, Joe': '@RepJoeWilson',
                    'Wilson, Frederica': '@RepWilson',
                    'Wittman, Robert': '@RobWittman',
                    'Womack, Steve': '@Rep_SteveWomack',
                    'Woodall, Rob': '@RepRobWoodall',
                    'Wyden, Ron': '@RonWyden',
                    'Yarmuth, John': '@RepJohnYarmuth',
                    'Yoder, Kevin': '@RepKevinYoder',
                    'Young, Don': '@RepDonYoung',
                    'Young, Todd': '@SenToddYoung',
                    'Heller, Dean': '@SenDeanHeller',
                    'Amodei, Mark': '@MarkAmodeiNV2',
                    'Bonamici, Suzanne': '@RepBonamici',
                    'DelBene, Suzan': '@RepDelBene',
                    'Massie, Thomas': '@RepThomasMassie',
                    'Payne, Donald': '@RepDonaldPayne',
                    'Schatz, Brian': '@SenBrianSchatz',
                    'Foster, Bill': '@RepBillFoster',
                    'Titus, Dina': '@RepDinaTitus',
                    'Cotton, Tom': '@SenTomCotton',
                    'Sinema, Kyrsten': '@RepSinema',
                    'LaMalfa, Doug': '@RepLaMalfa',
                    'Huffman, Jared': '@RepHuffman',
                    'Bera, Ami': '@RepBera',
                    'Cook, Paul': '@RepPaulCook',
                    'Swalwell, Eric': '@RepSwalwell',
                    'Valadao, David': '@RepDavidValadao',
                    'Brownley, Julia': '@JuliaBrownley26',
                    'Cardenas, Tony': '@RepCardenas',
                    'Ruiz, Raul': '@CongressmanRuiz',
                    'Takano, Mark': '@RepMarkTakano',
                    'Lowenthal, Alan': '@RepLowenthal',
                    'Vargas, Juan': '@RepJuanVargas',
                    'Peters, Scott': '@RepScottPeters',
                    'Esty, Elizabeth': '@RepEsty',
                    'Yoho, Ted': '@RepTedYoho',
                    'DeSantis, Ron': '@RepDeSantis',
                    'Frankel, Lois': '@RepLoisFrankel',
                    'Collins, Doug': '@RepDougCollins',
                    'Gabbard, Tulsi': '@TulsiPress',
                    'Duckworth, Tammy': '@SenDuckworth',
                    'Davis, Rodney': '@RodneyDavis',
                    'Bustos, Cheri': '@RepCheri',
                    'Walorski, Jackie': '@RepWalorski',
                    'Brooks, Susan': '@SusanWBrooks',
                    'Messer, Luke': '@RepLukeMesser',
                    'Barr, Garland': '@RepAndyBarr',
                    'Warren, Elizabeth': '@SenWarren',
                    'Kennedy, Joseph': '@RepJoeKennedy',
                    'Delaney, John': '@RepJohnDelaney',
                    'King, Angus': '@SenAngusKing',
                    'Kildee, Daniel': '@RepDanKildee',
                    'Nolan, Richard': '@USRepRickNolan',
                    'Wagner, Ann': '@RepAnnWagner',
                    'Daines, Steve': '@SteveDaines',
                    'Hudson, Richard': '@RepRichHudson',
                    'Pittenger, Robert': '@RepPittenger',
                    'Meadows, Mark': '@RepMarkMeadows',
                    'Holding, George': '@RepHolding',
                    'Heitkamp, Heidi': '@SenatorHeitkamp',
                    'Cramer, Kevin': '@RepKevinCramer',
                    'Fischer, Deb': '@SenatorFischer',
                    'Kuster, Ann': '@RepAnnieKuster',
                    'Lujan Grisham, Michelle': '@RepLujanGrisham',
                    'Meng, Grace': '@RepGraceMeng',
                    'Jeffries, Hakeem': '@RepJeffries',
                    'Maloney, Sean': '@RepSeanMaloney',
                    'Collins, Chris': '@RepChrisCollins',
                    'Wenstrup, Brad': '@RepBradWenstrup',
                    'Beatty, Joyce': '@RepBeatty',
                    'Joyce, David': '@RepDaveJoyce',
                    'Bridenstine, Jim': '@RepJBridenstine',
                    'Mullin, Markwayne': '@RepMullin',
                    'Perry, Scott': '@RepScottPerry',
                    'Rothfus, Keith': '@KeithRothfus',
                    'Cartwright, Matthew': '@RepCartwright',
                    'Rice, Tom': '@RepTomRice',
                    'Cruz, Ted': '@SenTedCruz',
                    'Weber, Randy': '@TXRandy14',
                    "O'Rourke, Beto": '@RepBetoORourke',
                    'Castro, Joaquin': '@JoaquinCastrotx',
                    'Williams, Roger': '@RepRWilliams',
                    'Veasey, Marc': '@RepVeasey',
                    'Vela, Filemon': '@RepFilemonVela',
                    'Stewart, Chris': '@RepChrisStewart',
                    'Kaine, Timothy': '@SenKaineOffice',
                    'Kilmer, Derek': '@RepDerekKilmer',
                    'Heck, Denny': '@RepDennyHeck',
                    'Pocan, Mark': '@RepMarkPocan',
                    'Kelly, Robin': '@RepRobinKelly',
                    'Sanford, Marshall': '@RepSanfordSC',
                    'Smith, Jason': '@RepJasonSmith',
                    'Booker, Cory': '@senbookeroffice',
                    'Clark, Katherine': '@RepKClark',
                    'Byrne, Bradley': '@RepByrne',
                    'Brat, David': '@RepDaveBrat',
                    'Norcross, Donald': '@DonaldNorcross',
                    'Adams, Alma': '@RepAdams',
                    'Palmer, Gary': '@USRepGaryPalmer',
                    'Hill, French': '@RepFrenchHill',
                    'Westerman, Bruce': '@RepWesterman',
                    'McSally, Martha': '@RepMcSally',
                    'Gallego, Ruben': '@RepRubenGallego',
                    'DeSaulnier, Mark': '@RepDeSaulnier',
                    'Knight, Steve': '@SteveKnight25',
                    'Aguilar, Pete': '@reppeteaguilar',
                    'Lieu, Ted': '@RepTedLieu',
                    'Torres, Norma': '@NormaJTorres',
                    'Walters, Mimi': '@RepMimiWalters',
                    'Buck, Ken': '@RepKenBuck',
                    'Curbelo, Carlos': '@RepCurbelo',
                    'Carter, Buddy': '@RepBuddyCarter',
                    'Hice, Jody': '@congressmanhice',
                    'Loudermilk, Barry': '@RepLoudermilk',
                    'Allen, Rick': '@reprickallen',
                    'Blum, Rod': '@RepRodBlum',
                    'Young, David': '@RepDavidYoung',
                    'Bost, Mike': '@RepBost',
                    'Abraham, Ralph': '@RepAbraham',
                    'Graves, Garret': '@RepGarretGraves',
                    'Moulton, Seth': '@teammoulton',
                    'Poliquin, Bruce': '@RepPoliquin',
                    'Moolenaar, John': '@RepMoolenaar',
                    'Bishop, Mike': '@RepMikeBishop',
                    'Trott, Dave': '@repdavetrott',
                    'Dingell, Debbie': '@RepDebDingell',
                    'Lawrence, Brenda': '@RepLawrence',
                    'Emmer, Tom': '@RepTomEmmer',
                    'Rouzer, David': '@RepDavidRouzer',
                    'MacArthur, Tom': '@RepTomMacArthur',
                    'Watson Coleman, Bonnie': '@RepBonnie',
                    'Zeldin, Lee': '@RepLeeZeldin',
                    'Rice, Kathleen': '@RepKathleenRice',
                    'Stefanik, Elise': '@RepStefanik',
                    'Katko, John': '@RepJohnKatko',
                    'Russell, Steve': '@RepRussell',
                    'Costello, Ryan': '@RepRyanCostello',
                    'Boyle, Brendan': '@CongBoyle',
                    'Ratcliffe, John': '@RepRatcliffe',
                    'Hurd, Will': '@hurdonthehill',
                    'Babin, Brian': '@RepBrianBabin',
                    'Love, Mia': '@repmialove',
                    'Beyer, Donald': '@repdonbeyer',
                    'Comstock, Barbara': '@RepComstock',
                    'Plaskett, Stacey': '@staceyplaskett',
                    'Newhouse, Dan': '@RepNewhouse',
                    'Grothman, Glenn': '@RepGrothman',
                    'Mooney, Alex': '@RepAlexMooney',
                    'Jenkins, Evan': '@RepEvanJenkins',
                    'Amata, Aumua': '@RepAmata',
                    'Sullivan, Dan': '@SenDanSullivan',
                    'Perdue, David': '@sendavidperdue',
                    'Ernst, Joni': '@SenJoniErnst',
                    'Tillis, Thom': '@senthomtillis',
                    'Rounds, Mike': '@SenatorRounds',
                    'Walker, Mark': '@RepMarkWalker',
                    'Sasse, Benjamin': '@SenSasse',
                    'Donovan, Daniel': '@RepDanDonovan',
                    'Kelly, Trent': '@reptrentkelly',
                    'LaHood, Darin': '@RepLaHood',
                    'Davidson, Warren': '@WarrenDavidson',
                    'Hanabusa, Colleen': '@RepHanabusa',
                    'Comer, James': '@KYComer',
                    'Evans, Dwight': '@RepDwightEvans',
                    'Harris, Kamala': '@SenKamalaHarris',
                    'Kennedy, John': '@SenJohnKennedy',
                    'Hassan, Margaret': '@Senatorhassan',
                    'Cortez Masto, Catherine': '@sencortezmasto',
                    'Schneider, Bradley': '@repschneider',
                    'Shea-Porter, Carol': '@repsheaporter',
                    "O'Halleran, Tom": '@repohalleran',
                    'Biggs, Andy': '@RepAndyBiggsAZ',
                    'Khanna, Ro': '@RepRoKhanna',
                    'Panetta, Jimmy': '@RepJimmyPanetta',
                    'Carbajal, Salud': '@RepCarbajal',
                    'Barragan, Nanette': '@RepBarragan',
                    'Correa, J.': '@reploucorrea',
                    'Blunt Rochester, Lisa': '@RepBRochester',
                    'Gaetz, Matt': '@RepMattGaetz',
                    'Dunn, Neal': '@drnealdunnfl2',
                    'Rutherford, John': '@RepRutherfordFL',
                    'Lawson, Al': '@RepAlLawsonJr',
                    'Murphy, Stephanie': '@RepStephMurphy',
                    'Soto, Darren': '@RepDarrenSoto',
                    'Demings, Val': '@RepValDemings',
                    'Crist, Charlie': '@repcharliecrist',
                    'Mast, Brian': '@repbrianmast',
                    'Rooney, Francis': '@RepRooney',
                    'Ferguson, A.': '@RepDrewFerguson',
                    'Krishnamoorthi, Raja': '@congressmanraja',
                    'Banks, Jim': '@RepJimBanks',
                    'Hollingsworth, Trey': '@reptrey',
                    'Marshall, Roger': '@RepMarshall',
                    'Higgins, Clay': '@RepClayHiggins',
                    'Johnson, Mike': '@RepMikeJohnson',
                    'Brown, Anthony': '@RepAnthonyBrown',
                    'Raskin, Jamie': '@repraskin',
                    'Bergman, Jack': '@RepJackBergman',
                    'Mitchell, Paul': '@RepPaulMitchell',
                    'Lewis, Jason': '@RepJasonLewis',
                    'Budd, Ted': '@RepTedBudd',
                    'Bacon, Don': '@repdonbacon',
                    'Gottheimer, Josh': '@RepJoshG',
                    'Rosen, Jacky': '@repjackyrosen',
                    'Kihuen, Ruben': '@RepKihuen',
                    'Suozzi, Thomas': '@RepTomSuozzi',
                    'Espaillat, Adriano': '@RepEspaillat',
                    'Faso, John': '@RepJohnFaso',
                    'Tenney, Claudia': '@RepTenney',
                    'Fitzpatrick, Brian': '@repbrianfitz',
                    'Smucker, Lloyd': '@RepSmucker',
                    'Gonzalez-Colon, Jenniffer': '@repjenniffer',
                    'Kustoff, David': '@repdavidkustoff',
                    'Gonzalez, Vicente': '@RepGonzalez',
                    'Arrington, Jodey': '@RepArrington',
                    'Taylor, Scott': '@RepScottTaylor',
                    'McEachin, A.': '@RepMcEachin',
                    'Garrett, Thomas': '@Rep_Tom_Garrett',
                    'Jayapal, Pramila': '@RepJayapal',
                    'Gallagher, Mike': '@RepGallagher',
                    'Cheney, Liz': '@RepLizCheney',
                    'Strange, Luther': '@SenatorStrange',
                    'Estes, Ron': '@RepRonEstes'
                    }